[metadata]
name = chronumental
author = Theo Sanderson
author_email = theo@theo.io
description = Large timetrees
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/theosanderson/chronumental
license = MIT
license_files = LICENSE
project_urls =
    Bug Tracker = https://github.com/theosanderson/chronumental/issues
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
install_requires =
    numpyro>=0.10.1
    alive-progress>=3
    pandas>=2
    treeswift>=1.1.28
    scipy>=1.10
    xopen>=2.0.1
    numpy>=1.24
    jax>=0.4.18


[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    chronumental = chronumental:__main__.main
